# Use postgres/example user/password credentials
version: '3.5'

services:
#  backend-bank:
#    container_name: backend_container
#    image: bank:latest
#    ports:
#      - "8081:8080"
#    environment:
#      POSTGRESQL_IP: "postgres"
#      POSTGRESQL_PORT:  "5432"
#    networks:
#      - bank_network
#    restart: always
#    depends_on:
#      - postgres


  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - bank_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - bank_network
    restart: unless-stopped


networks:
  bank_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:


